---  
#- name: copying a list of files from controller to host using loop
  #copy:
    #src: "{{ item }}"
    #dest: "/var/www/html/{{ item }}"
  #loop: "{{ files_to_copy }}"
  #notify: Restart service


- name: Restart service
  sysvinit:
    name: "{{ package_name }}"
    state: restarted
 
